# CI pipeline
name: $(Date:yyyy.M.d)$(Rev:.r)

trigger:
  branches:
    include:
      - main
pr: none

pool:
  vmImage: "ubuntu-latest"

jobs:
  - job: Validate_Schemas
    displayName: "Validate Schemas"
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: templates/lint-and-test.yaml

  - job: Publish_Schemas
    displayName: "Publish Schemas"
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(Build.Repository.LocalPath)/schemas"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "$(Build.ArtifactStagingDirectory)/schemas.zip"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)/schemas.zip"
          artifactName: "schemas"
          publishLocation: "pipeline"
