name: Lint Check

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'packages/scenes-client/pnpm-lock.yaml'
      - run: pnpm install
      - name: Lint scenes client
        working-directory: packages/scenes-client
        run: pnpm lint
